### ISSUE TITLE
Objectives 4.x

### ISSUE THREAD

**Issue by Florent2305** [medInria/medInria-public#864]
This issues lists more or less global objectives to achieve during later subversions of medInria 4.
### Scenes
  - [ ] extract scenes functions (toXMLNode, fromXMLNode, medAbstractLayeredView::write, medAbstractLayeredView::restoreState). 
  - [ ] parameters don't format data to xml directly. We must use new software architecture. Parameters must exchange abstract representation with a specific IO class to read/write files in XML or other future format.

### Browser
  - [ ] Allow to view network and removal drives (related to #814)

### Notifications
  - [ ] Add a system of notifications 
 
### Filtering
  - Remove isolated voxels/pixels
    - [ ] Add capability to support non-binary mask like (-1024 of background, 10000 positive value) (related to #798)
  - Mask application
    - [ ] Add capability to support non-binary mask like (-1024 of background, 10000 positive value) (related to #588)
 
### Copyright and Licences
  - [ ] Enhance copyright (related to #543)
  - [ ] List licences used by third-parties
  - [ ] Provide links to sources of third-parties on website

**Comment by mathildemerle** [comment]
Added some suggestions of objectives: 

### Modularity 
 - [ ] [[dmg] modularity of dmg design](https://github.com/medInria/medInria-public/issues/866) to change the dmg icons, names.
 - [ ] Icons, names, description, theme needs to be easily changed in fork-projects. Idea: directory/json file with all the icons, text, image, etc.

### Packaging
 - [ ] Linux: a real package to install the software 

### GUI
 - [ ] [Improve Home page ergonomics and style](https://github.com/medInria/medInria-public/issues/446)

**Comment by mathildemerle** [comment]
The plugin shop could be listed?
